POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Christopher",
    "number": "058736482"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Jim",
    "number": "058002382"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Christopher"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "number": "058736482"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
}
