name: Lint NodeJS fullStackOpen-Part3

on: pull_request

permissions:
  contents: read

jobs:
  build:
    name: Node project part3

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies for part3
        run: npm ci

      - name: Lint part3
        run: npm run lint
